version: 0.2
phases:
  install:
    commands:
      - echo "Installing nothing, this is a simple HTML site"
  build:
    commands:
      - echo "Build started on `date`"
artifacts:
  files:
    - index.html
    - appspec.yml